### ISSUE TITLE
请教：你博客的/movies/页面是怎么弄得？

### ISSUE THREAD

**Issue by saltbo** [ghosthim/blog.api2u.cn#3]
RT

不是MD通过模板渲染的吧 在blog分支没看到md文件

不会是自己手撸的html吧。。

**Comment by ghosthim** [comment]
是通过一个 Hexo 插件实现的，插件 [Hexo-douban](https://github.com/mythsman/hexo-douban)
我这个博客的主题因为某些原因属性为 page 的 md 文件不能很好地渲染，所以就挂到导航下面了，当然不可能是手撸的啊哈哈哈哈哈!

**Comment by saltbo** [comment]
哈 我都忘了Hexo支持插件，我换Hugo很久了，Hugo没有插件。准备换VuePress了
